### ISSUE TITLE
Issue while installing

### ISSUE THREAD

**Issue by vforv** [hrueger/setup-nativescript#1]
I am trying to execute this on custom Mac runner 
```
🍺  android-sdk was successfully installed!
Process finished.
Installing new cmdline-tools.
/bin/mkdir undefined/cmdline-tools
mkdir: undefined: No such file or directory
##[error]Error: The process '/bin/mkdir' failed with exit code 1
```
That error I get any idea?

Missing pip on beging as well

**Comment by hrueger** [comment]
Hi @vforv,
To setup the Android SDK on MacOSX I'm actually using [this ](https://github.com/marketplace/actions/android-emulator-runner) third party action. After looking into their code, I think your error happens [here](https://github.com/ReactiveCircus/android-emulator-runner/blob/61dd774a5b2ad006fe0b6fc53f53086afc241653/src/sdk-installer.ts#L16). Can you try and run the [android-emulator-runner action](https://github.com/marketplace/actions/android-emulator-runner) itself?

From the `undefined/cmdline-tools` I assume, that `process.env.ANDROID_HOME` is undefined (See the same line as linked above).
Maybe they should check in their action if `ANDROID_HOME` exists and if not, set it?

If you can't run their action successfully, you should create an issue in their repo.

When they update their action, I'm happy to rebuild mine and publish a new release!

**Comment by vforv** [comment]
I decided to go other way...
This is good idea but it would be much more useful if follow Nativescript setup guide:
https://docs.nativescript.org/start/ns-setup-linux

**Comment by hrueger** [comment]
What do you mean? Do you have problems on linux to?
On non-custom runners all platforms work fine for me...

And as I don't have custom runners, I need some more info to help you.

**Comment by vforv** [comment]
I only tried on custom Mac runner...

**Comment by hrueger** [comment]
So did you create an issue in the [android-emulator-runner action repository](https://github.com/ReactiveCircus/android-emulator-runner)? If yes, please post a comment here with a link to the issue so that I can keep track of its state and update my action as soon as that issue is resolved.

**Comment by vforv** [comment]
I just simply added this repo to the pipeline
- uses: hrueger/setup-nativescript@v1.0.0

**Comment by hrueger** [comment]
Ok, for the MacOS setup process, my action uses [this action](https://github.com/ReactiveCircus/android-emulator-runner) in the background, because I think it doesn't make sense to reinvent the wheel.
Your error seem's to be thrown in their code, not in mine. So you should create an issue in their repository!

**Comment by hrueger** [comment]
Closing this as it is an issue of https://github.com/ReactiveCircus/android-emulator-runner.
